### ISSUE TITLE
Does it work on Macos?

### ISSUE THREAD

**Issue by bwl21** [tesla-software/chrome2pdf#4]
I tried to use this on macos but get errors.

```
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 737 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in 30_workshop/22_print-website/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200
Stack trace:
#0 30_workshop/22_print-website/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 30_workshop/22_print-website/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 30_workshop/22_print-website/vendor/guzzlehttp/guzzle/sr in 30_workshop/22_print-website/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 200
```
any idea? Thanks in advance

**Comment by karlomikus** [comment]
It should work, I don't have macOS to test on tho.

Try to increase timeout with `->setTimeout($microseconds)` method.
